version: '3' 

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile 
    image: my-langserve:latest
    container_name: my-langserve
    ports:
      - "8001:8001"
    env_file:
      - .env